# Generated by Django 4.0.4 on 2022-05-24 09:32

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0005_alter_recipe_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="picture_filename",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="picture",
            field=models.FileField(
                blank=True, null=True, upload_to=recipe.models.upload_location
            ),
        ),
    ]
