# Generated by Django 4.0.4 on 2022-05-31 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0007_recipe_servings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="ranking",
            new_name="ranting",
        ),
    ]
