# Generated by Django 4.0.4 on 2022-05-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_rename_ranking_recipe_ranting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ranting',
            new_name='rating',
        ),
    ]
