# Generated by Django 4.0.4 on 2022-06-17 11:12

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0012_alter_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="picture",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=recipe.models.upload_location,
            ),
        ),
    ]
