# Generated by Django 4.0.4 on 2022-06-25 13:44

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0013_alter_recipe_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="directions",
            field=models.CharField(max_length=2000, verbose_name="directions"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="duration",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="duration"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=180, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="picture",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=recipe.models.upload_location,
                verbose_name="picture",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="rating",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="rating"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="servings"
            ),
        ),
    ]
