# Generated by Django 4.0.4 on 2022-07-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0014_alter_recipe_directions_alter_recipe_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="servings"
            ),
        ),
    ]
