# Generated by Django 4.0.4 on 2022-06-25 13:44

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_description_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=category.models.upload_location, verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('1', 'time'), ('2', 'food'), ('3', 'cuisine')], default='1', max_length=10, verbose_name='type'),
        ),
    ]
