version: "3"

volumes:
  node_modules:
services:
  db:
    container_name: abocados-db
    image: postgres
    env_file:
      - ./.env
  server:
    container_name: abocados-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: "python manage.py runserver 0.0.0.0:3003"
    env_file:
      - .env
    volumes:
      - ./server:/app
    ports:
      - "3003:3003"
    depends_on:
      - db
  front-web:
    container_name: abocados-web
    restart: always
    build:
      context: ./front-web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./front-web:/app
      - node_modules:/app/node_modules
    env_file:
      - .env

  nginx:
    container_name: abocados-nginx
    build: ./nginx
    ports:
      - "3001:3001"
    depends_on:
      - front-web
