# Generated by Django 4.0.4 on 2022-05-24 10:18

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="picture_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.FileField(
                blank=True, null=True, upload_to=user.models.upload_location
            ),
        ),
    ]
