# Generated by Django 4.0.4 on 2024-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_role_user_saved_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo_user',
            field=models.BooleanField(default=False, verbose_name='is_demo_user'),
        ),
    ]
