name: Abocados CI

# on:
#   push:
#     branches: ['main']
#   pull_request:
#     branches: ['main']

on: push

env:
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: test
        run: echo "la key $DJANGO_SECRET_KEY"

      - name: Install dependencies
        run: make build

      - name: test

      - name: Run migrations
        run: make migrate_full

      - name: Run tests
        run: make test
