name: Build & Deploy
# on:
#   push:
#     branches: [main]
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and test app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DIGITAL_OCEAN_HOST}}
          key: ${{secrets.DIGITAL_OCEAN_TOKEN}}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_TOKEN_PASSPHRASE }}
          script: |
            cd abocados-2.0/
            git pull
            make build
            make migrate_full
            make test
            make run
