name: Build & Deploy
# on:
#   push:
#     branches: [main]
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.DIGITAL_OCEAN_HOST}}
          key: ${{secrets.DIGITAL_OCEAN_TOKEN}}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_TOKEN_PASSPHRASE }}

          script: |
            mkdir test
            cd test
            echo 'Deployment successful to digital ocean'
